services:
  sakila-db:
    build: ./sakila-db
    container_name: sakila-db
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - sakila-db-data:/var/lib/mysql
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    depends_on:
      - sakila-db
    env_file:
      - .env
  frontend:
    build: ./Frontend
    ports:
      - "5173:80"
    depends_on:
      - backend



volumes:
  sakila-db-data:
